### ISSUE TITLE
On clicking the fab

### ISSUE THREAD

**Issue by kaushikb1996** [sergiocasero/RevealFAB#4]
Its showing the animation for 2 ms and then closes

ERROR :

04-18 22:59:05.539 2096-2096/com.xyz.android E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: com.xyz.android, PID: 2096
                                                                     java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.Intent.migrateExtraStreamToClipData()' on a null object reference
                                                                         at android.app.Instrumentation.execStartActivity(Instrumentation.java:1572)
                                                                         at android.app.Activity.startActivityForResult(Activity.java:3934)
                                                                         at android.app.Activity.startActivityForResult(Activity.java:3894)
                                                                         at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:843)
                                                                         at android.app.Activity.startActivity(Activity.java:4221)
                                                                         at android.app.Activity.startActivity(Activity.java:4189)
                                                                         at com.sergiocasero.revealfab.RevealFAB$2.onAnimationEnd(RevealFAB.java:113)
                                                                         at android.view.RenderNodeAnimator.onFinished(RenderNodeAnimator.java:376)
                                                                         at android.animation.RevealAnimator.onFinished(RevealAnimator.java:43)
                                                                         at android.view.RenderNodeAnimator.callOnFinished(RenderNodeAnimator.java:483)
                                                                         at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                         at android.os.MessageQueue.next(MessageQueue.java:323)
                                                                         at android.os.Looper.loop(Looper.java:135)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5443)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
04-18 22:59:05.566 2096-2201/com.xyz.android I/Adreno: DequeueBuffer: dequeueBuffer failed
04-18 22:59:05.568 2096-2201/com.xyz.android I/Adreno: DequeueBuffer: dequeueBuffer failed
04-18 22:59:05.569 2096-2201/com.xyz.android I/Adreno: DequeueBuffer: dequeueBuffer failed
04-18 22:59:05.569 2096-2201/com.xyz.android I/Adreno: DequeueBuffer: dequeueBuffer failed
04-18 22:59:05.574 2096-2201/com.xyz.android W/OpenGLRenderer: swapBuffers encountered EGL_BAD_SURFACE on 0xb7d97eb0, halting rendering...

**Comment by sergiocasero** [comment]
Hello! I'm testing it with VM and works fine, can you copy/paste your code here please? :)

**Comment by kaushikb1996** [comment]
I can't give you the code as of now but I can tell you that I just followed your instructions exactly.
